### ISSUE TITLE
5.6b3 issues

### ISSUE THREAD

**Issue by cAyou66** [Unity-Technologies/graph-visualizer#1]
Hi ! 
The code is not compiling on 5.6b3, mostly because
using UnityEngine.Timeline;
using UnityEngine.Playables;

can't be found.

Any workarounds / updates ?

Thanks !

**Comment by neochaft** [comment]
Hi @cAyou66 ,

Currently, the tool can only be used with specific Unity internal builds that are not available to the public.

In any case, thanks for trying to use the Timeline Visualizer! :)
Regards.
