### ISSUE TITLE
Not compiling code in 2018.1.3f1

### ISSUE THREAD

**Issue by elhispano** [Unity-Technologies/graph-visualizer#12]
After adding the Grapth Visualizer form master branch, the project didn't compile because of the following error: "Type `UnityEngine.Playables.PlayableOutput' does not contain a definition for `GetSourceOutputPort' and no extension method `GetSourceOutputPort' of type `UnityEngine.Playables.PlayableOutput' could be found. Are you missing an assembly reference?"

I have renamed it to "GetSourceInputPort()" instead after finding this change in a GitHub repo: https://github.com/Unity-Technologies/UnityCsReference/blob/master/Runtime/Export/Director/PlayableOutputExtensions.deprecated.cs

**Comment by romainf-unity** [comment]
Thanks for reporting it, I'll fix that!

**Comment by romainf-unity** [comment]
Fixed by #13
